namespace BeamKit.RulePacks;

/// <summary>
/// One file generated by a rule-pack scaffold.
/// </summary>
public sealed record RulePackScaffoldFile
{
    /// <summary>
    /// Creates a scaffold file.
    /// </summary>
    public RulePackScaffoldFile(string relativePath, string content)
    {
        RelativePath = RulePackText.Required(relativePath, nameof(relativePath));
        Content = content ?? throw new ArgumentNullException(nameof(content));
    }

    /// <summary>
    /// Relative path within the scaffold directory.
    /// </summary>
    public string RelativePath { get; init; }

    /// <summary>
    /// File content.
    /// </summary>
    public string Content { get; init; }
}
