using BeamKit.Check;

namespace BeamKit.CiServer;

/// <summary>
/// Persisted server-side record for one BeamKit CI run.
/// </summary>
public sealed record HostedCiRunRecord
{
    /// <summary>
    /// Creates a hosted CI run record.
    /// </summary>
    public HostedCiRunRecord(string id, DateTimeOffset createdAtUtc, string syntheticCaseId, BeamKitCiRunRecord artifact)
    {
        Id = CiServerText.Required(id, nameof(id));
        CreatedAtUtc = createdAtUtc;
        SyntheticCaseId = CiServerText.Required(syntheticCaseId, nameof(syntheticCaseId));
        Artifact = artifact ?? throw new ArgumentNullException(nameof(artifact));
    }

    /// <summary>
    /// Server run id.
    /// </summary>
    public string Id { get; init; }

    /// <summary>
    /// UTC timestamp when the server created the run.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; init; }

    /// <summary>
    /// Synthetic case used for the run.
    /// </summary>
    public string SyntheticCaseId { get; init; }

    /// <summary>
    /// Full CI artifact generated by BeamKit.
    /// </summary>
    public BeamKitCiRunRecord Artifact { get; init; }

    /// <summary>
    /// Top-level run status.
    /// </summary>
    public BeamKitCheckStatus Status => Artifact.Status;

    /// <summary>
    /// Suggested process exit code for compatible CI systems.
    /// </summary>
    public int ExitCode => Artifact.ExitCode;
}
