using BeamKit.Check;

namespace BeamKit.CiServer;

/// <summary>
/// Persisted server-side record for one BeamKit CI run.
/// </summary>
public sealed record HostedCiRunRecord
{
    /// <summary>
    /// Creates a hosted CI run record.
    /// </summary>
    public HostedCiRunRecord(
        string id,
        DateTimeOffset createdAtUtc,
        string caseId,
        BeamKitCiRunRecord artifact,
        CiRunInputKind inputKind = CiRunInputKind.SyntheticCase)
    {
        Id = CiServerText.Required(id, nameof(id));
        CreatedAtUtc = createdAtUtc;
        CaseId = CiServerText.Required(caseId, nameof(caseId));
        Artifact = artifact ?? throw new ArgumentNullException(nameof(artifact));
        InputKind = inputKind;
    }

    /// <summary>
    /// Server run id.
    /// </summary>
    public string Id { get; init; }

    /// <summary>
    /// UTC timestamp when the server created the run.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; init; }

    /// <summary>
    /// Case key for the run. Synthetic runs use the synthetic case id; uploaded runs use the plan id.
    /// </summary>
    public string CaseId { get; init; }

    /// <summary>
    /// Source category for the run.
    /// </summary>
    public CiRunInputKind InputKind { get; init; }

    /// <summary>
    /// Backward-compatible alias for synthetic-only callers.
    /// </summary>
    public string SyntheticCaseId => CaseId;

    /// <summary>
    /// Full CI artifact generated by BeamKit.
    /// </summary>
    public BeamKitCiRunRecord Artifact { get; init; }

    /// <summary>
    /// Top-level run status.
    /// </summary>
    public BeamKitCheckStatus Status => Artifact.Status;

    /// <summary>
    /// Suggested process exit code for compatible CI systems.
    /// </summary>
    public int ExitCode => Artifact.ExitCode;
}
